### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by YellowZaki** [Jannyboy11/CustomRecipes#1]
First of all, the plugin doesn't seen to work. The commands don't work and recipes are not loaded.

I also get a lot of console errors which seems to be related to recipes:
https://pastebin.com/wTzQRzJq

Thanks.

I'm using 1.12 and the latest version compiled.

**Comment by Jannyboy11** [comment]
Have you even read the README.md?

**Comment by wouterdedroog** [comment]
https://goo.gl/images/thvj7w

**Comment by Jannyboy11** [comment]
Sorry if my answer seems rude. The readme states the plugin is still in early development. Not everything is supposed to work yet. What should work at this point are adding shaped recipes, adding shapeless recipes and adding nbt recipes. Nothing is yet saved to or loaded from disk. I'm closing this issue for now. Let me know if you still have problems with a fresh compile.
