### ISSUE TITLE
update 1.12

### ISSUE THREAD

**Issue by ShaneBeee** [Jannyboy11/CustomRecipes#4]
I updated to the new 1.12 plugin.
Thanks for that btw!

I never touched my original plugin folder, but since the update, none of the recipes are working.
I had created for example "emerald axe"
When I try create it in a crafting table, nothing happens.
Am I missing something?

**Comment by ShaneBeee** [comment]
SCRATCH THAT!
I read the discussion and realized the recipes do not convert.
BUT I did find the converter that guy posted, ran that and it worked :)

**Comment by Jannyboy11** [comment]
Glad it worked for you! I'm trying to find some time to implement a migration command in the plugin itself, I hope to have it completed next week.
