### ISSUE TITLE
Le plugin nest pas supporter 

### ISSUE THREAD

**Issue by Froggyp** [Jannyboy11/CustomRecipes#7]
Enfait le plugin n'est pas lu ... je pense qu'il n'est pas compatible ... Et n'est donc pas lisible par mon serveur

**Comment by Jannyboy11** [comment]
I don't spreak French, but from what I understand is that the plugin is not compatible with your server. In the overview section on the spigot page there is a section that tells which version of CustomRecipes is compatible with which version of Spigot.
