### ISSUE TITLE
Ability to start from scratch.

### ISSUE THREAD

**Issue by j-k-h** [Jannyboy11/CustomRecipes#8]
This is potentially more of a feature request, but it seems as though the plugin comes with a bunch of custom recipes already created. Is it possible to remove all of them (besides removing them one by one). http://i.imgur.com/ASXfvf7.png

Edit: Seem to be hardcoded into the plugin? Not part of the files from what I can see.

**Comment by Jannyboy11** [comment]
Those are the default vanilla recipes, you can remove those by removing the corresponding json files from your server jar. Jar files are actually just zip files with some extra metadata, so you can use any zip tool such as 7zip or winrar to do this. The location in the jar is /assets/minecraft/recipes.
